### ISSUE TITLE
avoid new components per each render

### ISSUE THREAD

**Issue by WebReflection** [codemix/babel-plugin-hyperhtml#2]
the following will create a new Greet every render time
```js
class DemoComponent extends Component {
  render() {
     return this.html`<div class="test">
         ${new Greet({name: "Alice", class: "greeter"})}
         <p>This is some text</p>
       </div>`;
  }
}
```

It'd be awesome if inner components could be related to their owner. At the end of the day, writing `<Greet />` is not less static than a `div` so ... how about some helper to make it possible?

```js
// used for every component
const comp = (self, i, Class, data) => {
  // either quick and dirty or via WeakMap
  const c = (self.__comp || (self.__comp = []))[i] ||
            (self.__comp[i] = new Class);
  c.setState(data);
  return c;
};

class DemoComponent extends Component {
  get defaultState() { return {class: null, name: ''}; }
  render() {
    return this.html`
      <div class="test">
        ${comp(this, 0, Greet, {name: "Alice", class: "greeter"})}
      <p>This is some text</p>
    </div>`;
  }
}

class Greet extends Component {
  render() {
    return this.html`
      <div class=${this.state.class}>
        <h1>Hi ${this.state.name}</h1>
      </div>`;
  }
}
```

The `i` in the `comp` helper is the index of the component. In this way you update the same component each time instead of creating a new one.

If the `setState(data)` is not a good pattern, then the component should expose a way to be updated or its render should look for `props`.

```js
const comp = (self, i, Class, props) => {
  const c = (self.__comp || (self.__comp = []))[i] ||
            (self.__comp[i] = new Class);
  // set props and return the rendered/updated node
  c.props = props;
  return c.render();
};

// ... same code as before ...

class Greet extends Component {
  render() {
    return this.html`
      <div class=${this.props.class}>
        <h1>Hi ${this.props.name}</h1>
      </div>`;
  }
}
```

**Thoughts ?**

**Comment by phpnode** [comment]
(github ate my content again so will clarify the following a bit tomorrow):

So this is a bit similar to the concept of keys in React. In many cases it's possible to generate the key automatically (as React does for static fragments of JSX), but this stops working as soon as you do something like a loop, you need to specify the `key` explicitly:
```js
const List = ({items}) => (
  <ul>
    {items.map(item => <li key={item.id}>{item.name}</li>}
  </ul>
);
```

I think we'd need a function similar to react's `createElement()` as part of core, it should be able to deal with instantiating and updating both function based and class based components.

**Comment by WebReflection** [comment]
hyperHTML is "keyed" by default and doesn't make sense otherwise ... we need to find a compromise that makes sense on the DOM world, if this would just repeat whatever React does, I don't see any value in having hyperHTML as alternative fallback :man_shrugging:

**Comment by WebReflection** [comment]
any progress on this, or any way we can move forward?

**Comment by phpnode** [comment]
@WebReflection still interested but haven't had much time recently, PRs / proposals very welcome

**Comment by WebReflection** [comment]
so ... I've released 2.5 which has a could of interesting things in it:
  * it supports self-closing tags, making JSX basically redundant when you use Custom Elements
  * it can easily let you hook into any element, [as shown in this thread](https://twitter.com/WebReflection/status/954471671649505281)

What does it mean for this prototype?

It means you could have:
```js
import {wire, Component} from 'hyperhtml';

class Greet {
  constructor(el) {
    this.el = el;
    this.render(el.getAttribute('name'));
  }
  render(name, ...extra) {
    hyperHTML(this.el)
    `<h1>Hi ${name}</h1>`;
  }
}

class DemoComponent extends Component {
  render() {
     return (
       <div class="test">
         <div onconnected=${is('Greet')} name="Alice" class="greeter" />
         <p>This is some text</p>
       </div>
     );
  }
}

function is(name) {
  var callback = is.bound[name];
  if (!callback) {
    callback = (is.bound[name] = function (e) {
      var component = is.component.get(e.currentTarget);
      if (!component) is.component.set(
        e.currentTarget,
        (component = new is[name](e.currentTarget))
      );
      return component;
    });
  }
  return callback;
}
is.bound = Object.create(null);
is.component = new WeakMap;
is.define = function (name, constructor) {
  is[name] = constructor;
};
```

thoughts ?

**Comment by WebReflection** [comment]
sad to see this is death already. Closing this bug since it sits without a future in my list of issues.

**Comment by phpnode** [comment]
@WebReflection apologies - I haven't had time to investigate hyperHTML more for the last few months, happy to transfer this repo somewhere if you'd like to continue with it.
